# Generated by Django 3.0.4 on 2020-03-17 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petclinic', '0002_auto_20200317_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=1000)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petclinic.Pet')),
            ],
        ),
    ]
