# Generated by Django 3.0.4 on 2020-03-21 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petclinic', '0004_auto_20200318_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='name',
            field=models.CharField(default='jogging', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='petclinic.Owner'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='petclinic.PetType'),
        ),
        migrations.AlterField(
            model_name='vet',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vets', to='petclinic.Specialty'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='petclinic.Pet'),
        ),
    ]
