# Generated by Django 3.0.4 on 2020-03-21 15:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('petclinic', '0005_auto_20200321_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 15, 2, 0, 904259, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 15, 2, 21, 108551, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 15, 2, 32, 236739, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 15, 2, 38, 955469, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pettype',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 15, 2, 45, 460502, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pettype',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 15, 2, 51, 535477, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialty',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 15, 2, 59, 815475, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialty',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 15, 3, 7, 869695, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vet',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 15, 3, 13, 786902, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vet',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 15, 3, 20, 116909, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 15, 3, 28, 44980, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 15, 3, 41, 146833, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
