# Generated by Django 3.0.4 on 2020-03-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petclinic', '0007_auto_20200327_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettype',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
